### PR TITLE
Implemented a new method for releasing event listeners from DOM

### PR DESCRIPTION
**Pull request by eliamartani**
## Related Issue
Issue #360

## Your solution
In this PR:
- I have separated methods from any `addEventListener` to be able to release it
- Created a new method called `destroy` and exposed it at `export`
- Created a test to check if this new method is defined

## How Has This Been Tested?
- By running `npm run test`
- Creating AOS and destroying it
    - Also checked `getEventListeners(window)` and `getEventListeners(document)` to see remaining listeners

### CODE REVIEW

**Comment by ncoden** [comment]
Hi @eliamartani 👋,

There is some linting errors. See https://travis-ci.org/michalsnik/aos/builds/401775997#L470.

This should be on a single line:
https://github.com/michalsnik/aos/blob/0fb1399fe1e02dae2af6cfcab2a474712dd690b8/src/js/aos.js#L57-L60

**Comment by eliamartani** [comment]
> Hi @eliamartani 👋,
> 
> There is some linting errors. See https://travis-ci.org/michalsnik/aos/builds/401775997#L470.
> 
> This should be on a single line:
> [aos/src/js/aos.js](https://github.com/michalsnik/aos/blob/0fb1399fe1e02dae2af6cfcab2a474712dd690b8/src/js/aos.js#L57-L60)
> 
> Lines 57 to 60 in [0fb1399](/michalsnik/aos/commit/0fb1399fe1e02dae2af6cfcab2a474712dd690b8)
> 
>  window.addEventListener( 
>    'scroll', 
>    scrollEvent 
>  );

Done 😄

**Comment by oguilleux** [comment]
Hi guys !

Just tested `AOS.destroy()` and it doesn't seem to work. Has it been implemented ?

Thanks

**Comment by eliamartani** [comment]
I'm closing this PR. Can't help with this anymore.

**Pull request closed without merging**
